In [2]:
import numpy as np

In [3]:
# 0D tensor or Scaler.

In [4]:
zeroD_tensor = np.array(3)
zeroD_tensor

array(3)

In [5]:
# 1D tensor or vector. 

In [6]:
oneD_tensor = np.array([1, 2, 3, 4, 5])

oneD_tensor

array([1, 2, 3, 4, 5])

In [18]:
oneD_tensor.ndim

1

In [7]:
# 1. It is a vector of dimension 5.
# 2. But it is tensor of 1 dimension. 

In [8]:
# 2D tensor or matrix. 

In [16]:
twoD_tensor = np.array([[1, 2, 3], [4, 5, 6]])
twoD_tensor

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
twoD_tensor.ndim

2

In [10]:
# 3D_tensor 

In [13]:
threeD_tensor = np.array([[[1], [3]], [[4], [6]]] )
threeD_tensor

array([[[1],
        [3]],

       [[4],
        [6]]])

In [14]:
threeD_tensor.ndim

3